import Link from "next/link";
import {
  Activity,
  Apple,
  ArrowUpRight,
  Atom,
  BookOpen,
  CheckCircle2,
  Cpu,
  Database,
  Download,
  FileSpreadsheet,
  FlaskConical,
  Gauge,
  HardDrive,
  LineChart,
  Microscope,
  MonitorDown,
  ShieldCheck,
  Workflow,
} from "lucide-react";
import { ProductSpectralCanvas } from "@/components/ProductSpectralCanvas";

const diagnostics = [
  {
    icon: Atom,
    title: "NIST-backed atomic analysis",
    body: "Line identification and relative optically thin atomic forward models with wavelength shift, species scales, instrument width, baseline, residuals, and contribution tables.",
  },
  {
    icon: Activity,
    title: "Molecular band fitting",
    body: "Validated molecular line databases for OH(A-X), N2(C-B), N2+(B-X), NH(A-X), and NO(B-X), with Trot/Tvib and state-by-state population workflows.",
  },
  {
    icon: Gauge,
    title: "Electron density",
    body: "H-alpha Stark workflow from the lab MATLAB chain: Voigt widths, instrument deconvolution, vdW subtraction, Gigosos conversion, uncertainty, and warnings.",
  },
  {
    icon: Workflow,
    title: "Recipe-driven batches",
    body: "Save analysis configurations and run them across experiment matrices, then export long-form CSV/XLSX tables for downstream plotting or statistics.",
  },
];

const heroMetrics = [
  ["10k+", "NIST rows"],
  ["5", "molecular DBs"],
  ["DMG / EXE", "desktop builds"],
];

const workflow = [
  {
    title: "Import and QA",
    body: "Load CSV, TXT, TSV, ASC, DAT, or XLSX spectra, parse metadata, and catch saturation, drift, spacing, SNR, and coverage problems.",
  },
  {
    title: "Preprocess",
    body: "Crop, baseline, smooth, remove spikes, normalize, and calibrate wavelength before fitting.",
  },
  {
    title: "Fit diagnostics",
    body: "Run peaks, molecular bands, electron density, or atomic forward models with visible assumptions and residuals.",
  },
  {
    title: "Batch and export",
    body: "Save recipes, process experiment matrices, and export CSV/XLSX/PDF reports with provenance.",
  },
];

const requirements = [
  {
    platform: "macOS",
    icon: Apple,
    href: "/downloads/mac",
    cta: "Download DMG",
    detail: "macOS 12 or later. Apple Silicon build is available locally; Intel builds are generated by release CI.",
    specs: ["Apple Silicon or Intel Mac", "8 GB RAM minimum", "16 GB RAM recommended for batches", "No Python or Node install required"],
  },
  {
    platform: "Windows",
    icon: MonitorDown,
    href: "/downloads/windows",
    cta: "Download EXE",
    detail: "Windows 10/11 x64 NSIS installer from the release workflow.",
    specs: ["Windows 10 or 11", "x64 processor", "8 GB RAM minimum", "700 MB free disk space recommended"],
  },
];

const trustItems = [
  "NIST-derived atomic line catalog with optional live ASD refresh coverage",
  "Validated molecular line databases bundled into desktop builds",
  "Explicit labels for reference-backed, software-tested, lab-port, and validation status",
  "No hidden black-box correction layer: fit parameters, assumptions, and warnings stay visible",
];

export const dynamic = "force-dynamic";

export default function ProductHomePage() {
  return (
    <div className="product-site bg-[#07111f] text-white">
      <section className="relative overflow-hidden border-b border-white/10">
        <ProductSpectralCanvas />
        <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(7,17,31,0.97)_0%,rgba(7,17,31,0.88)_54%,rgba(7,17,31,0.62)_100%)]" />
        <div className="relative mx-auto grid min-h-[720px] max-w-[1320px] items-center gap-10 px-5 py-14 lg:grid-cols-[minmax(0,1fr)_minmax(360px,0.66fr)] lg:px-8 xl:gap-14">
          <div className="max-w-[760px]">
            <div className="mb-5 flex w-fit items-center gap-2 border border-white/15 bg-white/10 px-3 py-2 text-sm text-slate-200 backdrop-blur-xl" style={{ borderRadius: 8 }}>
              <FlaskConical className="h-4 w-4 text-[#60d3ff]" />
              Optical emission spectroscopy for low-temperature plasma
            </div>
            <h1 className="max-w-3xl text-5xl font-semibold leading-[1.04] text-white md:text-6xl">
              PlasmaSpec Studio
            </h1>
            <p className="mt-6 max-w-2xl text-lg leading-8 text-slate-200">
              A research workstation for analyzing plasma spectra, from raw OES files to traceable diagnostics.
              Built for non-thermal plasma researchers who need line data, fits, batches, exports, and scientific
              warnings in one calm desktop tool.
            </p>
            <div className="mt-8 flex flex-col gap-3 sm:flex-row sm:flex-wrap">
              <Link href="/downloads/mac" className="landing-primary-button">
                <Download className="h-5 w-5" />
                macOS DMG
              </Link>
              <Link href="/downloads/windows" className="landing-secondary-button">
                <MonitorDown className="h-5 w-5" />
                Windows EXE
              </Link>
              <Link href="/studio" className="landing-ghost-button">
                Open web studio
                <ArrowUpRight className="h-5 w-5" />
              </Link>
            </div>
            <div className="mt-8 grid max-w-2xl gap-0 overflow-hidden border border-white/12 bg-white/[0.07] text-sm text-slate-300 backdrop-blur-xl sm:grid-cols-3" style={{ borderRadius: 8 }}>
              {heroMetrics.map(([value, label]) => (
                <div key={label} className="border-b border-white/10 px-4 py-3 sm:border-b-0 sm:border-r sm:last:border-r-0">
                  <span className="block text-xl font-semibold text-white">{value}</span>
                  <span>{label}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="flex min-w-0 items-center justify-center lg:justify-end">
            <div className="product-window w-full max-w-[500px] overflow-hidden border border-white/18 bg-slate-950/60 shadow-2xl backdrop-blur-2xl">
              <div className="flex items-center justify-between border-b border-white/10 px-4 py-3">
                <div className="flex items-center gap-2">
                  <span className="h-2.5 w-2.5 bg-[#ff6270]" style={{ borderRadius: 99 }} />
                  <span className="h-2.5 w-2.5 bg-[#ffb74d]" style={{ borderRadius: 99 }} />
                  <span className="h-2.5 w-2.5 bg-[#60d3ff]" style={{ borderRadius: 99 }} />
                </div>
                <div className="text-xs text-slate-400">spectrum-044</div>
              </div>
              <div className="p-4">
                <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
                  <div>
                    <div className="text-sm font-semibold text-white">N2(C-B) molecular fit</div>
                    <div className="text-xs text-slate-400">337.1 nm bandhead · Voigt profile</div>
                  </div>
                  <div className="border border-[#60d3ff]/35 bg-[#60d3ff]/10 px-3 py-1 text-xs font-medium text-[#9deaff]" style={{ borderRadius: 99 }}>
                    review warnings
                  </div>
                </div>
                <div className="relative h-[250px] overflow-hidden border border-white/10 bg-[#081526]" style={{ borderRadius: 8 }}>
                  <div className="absolute inset-x-0 bottom-10 h-px bg-white/12" />
                  <div className="absolute inset-y-8 left-12 w-px bg-white/12" />
                  <svg viewBox="0 0 620 260" className="h-full w-full" role="img" aria-label="Product spectrum fit preview">
                    <polyline
                      points="0,204 40,201 80,198 112,190 136,160 148,96 160,169 190,194 230,190 252,158 270,88 286,152 312,190 350,184 380,142 398,74 418,151 452,186 488,181 520,128 536,90 550,147 586,178 620,182"
                      fill="none"
                      stroke="#60d3ff"
                      strokeWidth="3"
                    />
                    <polyline
                      points="0,207 45,203 84,199 120,189 140,153 151,109 165,171 198,196 238,191 256,160 271,101 291,156 320,189 354,183 382,145 399,86 420,150 456,184 492,181 522,132 538,97 556,150 590,178 620,181"
                      fill="none"
                      stroke="#ffb74d"
                      strokeWidth="2"
                      strokeDasharray="5 6"
                    />
                    <g stroke="rgba(255,255,255,0.16)" strokeWidth="1">
                      <line x1="151" x2="151" y1="38" y2="218" />
                      <line x1="271" x2="271" y1="38" y2="218" />
                      <line x1="399" x2="399" y1="38" y2="218" />
                      <line x1="538" x2="538" y1="38" y2="218" />
                    </g>
                  </svg>
                </div>
                <div className="mt-4 grid grid-cols-3 overflow-hidden border border-white/10 bg-white/[0.07] text-sm" style={{ borderRadius: 8 }}>
                  {[
                    ["Trot", "416 K"],
                    ["Tvib", "3180 K"],
                    ["sigma", "0.18 nm"],
                  ].map(([label, value]) => (
                    <div key={label} className="border-r border-white/10 px-3 py-3 last:border-r-0">
                      <div className="text-xs text-slate-400">{label}</div>
                      <div className="mt-1 font-semibold text-white">{value}</div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section id="download" className="product-light-section px-5 py-16 lg:px-8">
        <div className="mx-auto grid max-w-[1240px] gap-8 lg:grid-cols-[0.72fr_1.28fr]">
          <div className="max-w-xl">
            <p className="landing-eyebrow">Desktop downloads</p>
            <h2 className="mt-3 text-4xl font-semibold leading-tight">Install it like a real lab tool.</h2>
            <p className="product-section-copy mt-4 text-base leading-7">
              The desktop builds bundle the frontend, FastAPI backend, NIST catalog, and molecular line databases.
              Users do not need to install Python, Node, or database files separately.
            </p>
          </div>
          <div className="grid gap-5 md:grid-cols-2">
            {requirements.map((item) => (
              <article key={item.platform} className="download-card p-6">
                <div className="flex items-start gap-4">
                  <div className="product-icon-tile flex h-11 w-11 flex-none items-center justify-center" style={{ borderRadius: 8 }}>
                    <item.icon className="h-5 w-5" />
                  </div>
                  <div>
                    <h3 className="text-xl font-semibold">{item.platform}</h3>
                    <p className="mt-1 text-sm leading-6">{item.detail}</p>
                  </div>
                </div>
                <Link href={item.href} className="mt-5 inline-flex min-h-11 w-full items-center justify-center gap-2 border border-[#0066ff] bg-[#0066ff] px-4 py-2 text-sm font-semibold text-white shadow-thin transition hover:bg-[#0052cc]" style={{ borderRadius: 8 }}>
                  <Download className="h-4 w-4" />
                  {item.cta}
                </Link>
                <ul className="mt-5 grid gap-2 text-sm">
                  {item.specs.map((spec) => (
                    <li key={spec} className="flex gap-2">
                      <CheckCircle2 className="mt-0.5 h-4 w-4 flex-none" />
                      <span>{spec}</span>
                    </li>
                  ))}
                </ul>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section className="product-light-section-alt px-5 py-16 lg:px-8">
        <div className="mx-auto max-w-[1240px]">
          <div className="mb-8 flex flex-col justify-between gap-4 lg:flex-row lg:items-end">
            <div className="max-w-3xl">
              <p className="landing-eyebrow">Analysis capabilities</p>
              <h2 className="mt-3 text-4xl font-semibold leading-tight">Feature depth for low-temperature plasma researchers.</h2>
            </div>
            <p className="max-w-md text-sm leading-6 text-[#52657a]">
              Capabilities are grouped by the decisions researchers make during an experiment, so the page scans instead of stacking every feature at once.
            </p>
          </div>
          <div className="grid gap-5 md:grid-cols-2">
            {diagnostics.map((item) => (
              <article key={item.title} className="feature-card flex gap-4 p-6">
                <div className="product-icon-tile flex h-11 w-11 flex-none items-center justify-center" style={{ borderRadius: 8 }}>
                  <item.icon className="h-5 w-5" />
                </div>
                <div>
                  <h3 className="text-lg font-semibold">{item.title}</h3>
                  <p className="mt-2 text-sm leading-6">{item.body}</p>
                </div>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section className="bg-[#0c1626] px-5 py-16 text-white lg:px-8">
        <div className="mx-auto grid max-w-[1240px] gap-8 lg:grid-cols-[0.9fr_1.1fr]">
          <div>
            <p className="landing-eyebrow text-[#60d3ff]">Research workflow</p>
            <h2 className="mt-3 text-4xl font-semibold leading-tight">From raw spectrum to publishable analysis trail.</h2>
            <p className="mt-4 text-base leading-7 text-slate-300">
              PlasmaSpec Studio is designed to make the intermediate values visible, so a fit is not just a number.
              Each result carries preprocessing history, fit parameters, residuals, uncertainty, warnings, and provenance.
            </p>
          </div>
          <div className="workflow-list">
            {workflow.map((step, index) => (
              <div key={step.title} className="glass-step flex gap-4 border border-white/10 bg-white/10 p-5 backdrop-blur-xl">
                <div className="flex h-8 w-8 flex-none items-center justify-center bg-[#0066ff] text-sm font-semibold text-white" style={{ borderRadius: 8 }}>
                  {index + 1}
                </div>
                <div>
                  <h3 className="font-semibold text-white">{step.title}</h3>
                  <p className="mt-1 text-sm leading-6 text-slate-300">{step.body}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="product-light-section px-5 py-16 lg:px-8">
        <div className="mx-auto grid max-w-[1240px] gap-8 lg:grid-cols-[1fr_1fr]">
          <div className="feature-card p-6">
            <div className="mb-5 flex items-center gap-3">
              <Database className="h-6 w-6 text-[#0066ff]" />
              <h2 className="text-3xl font-semibold">Line data and provenance</h2>
            </div>
            <ul className="grid gap-3">
              {trustItems.map((item) => (
                <li key={item} className="flex gap-3 text-sm leading-6">
                  <ShieldCheck className="mt-0.5 h-5 w-5 flex-none text-[#0066ff]" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>

          <div className="feature-card p-6">
            <div className="mb-5 flex items-center gap-3">
              <BookOpen className="h-6 w-6 text-[#0066ff]" />
              <h2 className="text-3xl font-semibold">What researchers get</h2>
            </div>
            <div className="grid gap-3 sm:grid-cols-2">
              {[
                [LineChart, "Spectrum QA", "Know when data quality can bias a fit."],
                [FileSpreadsheet, "CSV/XLSX exports", "Move clean results into papers and notebooks."],
                [Cpu, "Local execution", "Data stays on the researcher machine."],
                [HardDrive, "Bundled databases", "Reference data ships with the desktop app."],
              ].map(([Icon, title, body]) => (
                <div key={String(title)} className="researcher-get-card p-4" style={{ borderRadius: 8 }}>
                  <Icon className="mb-3 h-5 w-5 text-[#0066ff]" />
                  <h3 className="font-semibold">{title as string}</h3>
                  <p className="mt-2 text-sm leading-6">{body as string}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      <section className="relative overflow-hidden bg-[#07111f] px-5 py-16 text-white lg:px-8">
        <div className="absolute inset-x-0 top-0 h-px bg-[linear-gradient(90deg,transparent,rgba(96,211,255,0.65),transparent)]" />
        <div className="mx-auto max-w-[1240px]">
          <div className="community-panel border border-white/15 bg-white/10 p-7 backdrop-blur-2xl">
            <p className="landing-eyebrow text-[#60d3ff]">Community contribution</p>
            <h2 className="mt-3 max-w-4xl text-4xl font-semibold leading-tight">
              Created as a contribution to the non-thermal plasma diagnostics community by Chidera Innocent.
            </h2>
            <p className="mt-4 max-w-3xl text-base leading-7 text-slate-300">
              The goal is a practical, inspectable tool for researchers who need faster OES workflows without losing the
              scientific chain of custody behind each diagnostic result.
            </p>
            <div className="mt-7 flex flex-col gap-3 sm:flex-row">
              <Link href="/studio" className="landing-primary-button">
                <Microscope className="h-5 w-5" />
                Explore the studio
              </Link>
              <a href="#download" className="landing-secondary-button">
                <MonitorDown className="h-5 w-5" />
                Get desktop builds
              </a>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
